# Generated by Django 3.1.5 on 2021-03-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210320_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
