# Generated by Django 3.1.5 on 2021-03-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210320_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='more_details',
            field=models.TextField(),
        ),
    ]
