# Generated by Django 3.1.5 on 2021-03-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210320_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='created',
        ),
    ]
