# Generated by Django 3.1.5 on 2021-03-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_joboffer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='industries',
            field=models.ManyToManyField(to='core.Industry'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='regions',
            field=models.ManyToManyField(to='core.Region'),
        ),
    ]
